export const dynamic = 'force-dynamic';

import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import ContactForm from './ContactForm';

export default function OrganizationsPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      <main className="flex-1 w-full">


        {/* ── Hero ── */}
        <section className="bg-gray-900 py-24 px-4 text-center">
          <div className="max-w-4xl mx-auto">
            <h1 className="text-4xl md:text-6xl font-montserrat font-extrabold text-white mb-6">
              Turn Values into Visuals.
            </h1>
            <p className="text-xl text-gray-400 mb-10 max-w-2xl mx-auto">
              Bring COMMUNITREE &amp; EZONE to your School, NGO, or Company.
            </p>
            <div className="flex flex-col sm:flex-row gap-6 justify-center items-center mb-12">
              <div className="bg-gray-800 p-6 rounded-xl border border-gray-700 max-w-sm w-full">
                <div className="text-red-400 font-bold mb-2">The Old Way</div>
                <div className="text-gray-300 text-sm">Boring email pledge. No visual proof. No virality.</div>
              </div>
              <div className="text-gray-500 font-bold hidden sm:block">VS</div>
              <div className="bg-teal-900/30 p-6 rounded-xl border border-teal-500/30 max-w-sm w-full">
                <div className="text-teal-400 font-bold mb-2">The COMMUNITREE &amp; EZONE Way</div>
                <div className="text-gray-300 text-sm">Instant branded poster. Social sharing. Trackable participation.</div>
              </div>
            </div>
            <a href="#contact-form" className="inline-block bg-teal-400 text-gray-900 rounded-full px-8 py-4 font-bold hover:bg-teal-300 transition-colors">
              Get Your Custom Pledge Program
            </a>
          </div>
        </section>

        {/* ── How It Works ── */}
        <section className="py-20 px-4 bg-white">
          <div className="max-w-7xl mx-auto">
            <h2 className="text-3xl font-montserrat font-bold text-center text-gray-900 mb-16">How It Works</h2>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-12 text-center">
              {[
                { n: '1', title: 'You Connect', body: 'Fill the form below, and we create your custom pledge page with your branding.' },
                { n: '2', title: 'Your Team Acts', body: 'Your community pledges, ticks commitments, and downloads their branded poster.' },
                { n: '3', title: 'You Track', body: 'We share a summary of your community’s participation — who pledged and took part.' },
              ].map(s => (
                <div key={s.n}>
                  <div className="w-16 h-16 bg-teal-100 text-teal-600 rounded-full flex items-center justify-center font-bold text-2xl mx-auto mb-6">{s.n}</div>
                  <h3 className="text-xl font-bold text-gray-900 mb-3">{s.title}</h3>
                  <p className="text-gray-600">{s.body}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ── What Orgs Get ── */}
        <section className="py-20 px-4 bg-gray-50 border-t border-gray-200">
          <div className="max-w-7xl mx-auto">
            <h2 className="text-3xl font-montserrat font-bold text-center text-gray-900 mb-16">What You Get</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              {[
                { icon: '🎯', title: 'Your Brand, Their Commitment', body: "Your organisation's logo is watermarked on every poster generated by your community." },
                { icon: '📊', title: 'Participation Summaries', body: "A clear summary of your community's pledges and quiz participation." },
                { icon: '🏅', title: 'The Branded Certificate', body: 'A co-branded, frame-worthy PNG certificate for every participant.' },
                { icon: '✨', title: 'Custom Pledge Creation', badge: 'Premium', body: 'Work with us to design a bespoke pledge challenge exclusive to your organisation.' },
              ].map(item => (
                <div key={item.title} className="bg-white p-8 rounded-2xl border border-gray-100 shadow-sm flex items-start gap-4 relative overflow-hidden">
                  {item.badge && (
                    <div className="absolute top-4 right-4 bg-yellow-100 text-yellow-800 text-xs font-bold px-3 py-1 rounded-full">{item.badge}</div>
                  )}
                  <div className="text-3xl">{item.icon}</div>
                  <div>
                    <h3 className="text-xl font-bold text-gray-900 mb-2">{item.title}</h3>
                    <p className="text-gray-600">{item.body}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ── Contact Form ── */}
        <section id="contact-form" className="py-24 px-4 bg-white">
          <div className="max-w-3xl mx-auto">
            <div className="text-center mb-12">
              <h2 className="text-3xl font-montserrat font-bold text-gray-900 mb-4">Let&apos;s Create Impact Together</h2>
              <p className="text-gray-600">Complete the form below and we&apos;ll send you a mock-up within 24 hours.</p>
            </div>
            <div className="bg-gray-50 rounded-3xl p-8 md:p-12 border border-gray-100 shadow-sm">
              <ContactForm />
            </div>
          </div>
        </section>

      </main>
      <Footer />
    </div>
  );
}
